char *string_toupper(char *x);
void reverse_array(int *a, int n);
char *leet(char *);
char *_strncat(char *dest, char *src, int n);
int _putchar(char c);
char *_strncpy(char *dest, char *src, int n);
int _strcmp(char *s1, char *s2);
char *string_toupper(char *);
void print_number(int n);
char *cap_string(char *);
char *rot13(char *x);
